insert into public.projects (
  slug,
  title_hr,
  title_en,
  category_hr,
  category_en,
  excerpt_hr,
  excerpt_en,
  description_hr,
  description_en,
  client,
  year,
  services_hr,
  services_en,
  cover_image_url,
  gallery_image_urls,
  published,
  show_date,
  sort_order
)
values (
  'testni-projekt',
  'Testni projekt',
  'Test Project',
  'Web dizajn',
  'Web Design',
  'Kratki opis testnog projekta za provjeru Supabase povezivanja i prikaza na naslovnici.',
  'Short test project description for checking the Supabase connection and homepage display.',
  'Ovo je testni projekt dodan kroz SQL seed. Slike su namjerno prazne i mogu se dodati kasnije kroz admin sucelje.',
  'This is a test project added through an SQL seed. Images are intentionally empty and can be added later in the admin UI.',
  'Test Firma',
  '2026',
  array['Web dizajn', 'Frontend', 'Supabase'],
  array['Web Design', 'Frontend', 'Supabase'],
  null,
  '{}',
  true,
  true,
  0
)
on conflict (slug) do update set
  title_hr = excluded.title_hr,
  title_en = excluded.title_en,
  category_hr = excluded.category_hr,
  category_en = excluded.category_en,
  excerpt_hr = excluded.excerpt_hr,
  excerpt_en = excluded.excerpt_en,
  description_hr = excluded.description_hr,
  description_en = excluded.description_en,
  client = excluded.client,
  year = excluded.year,
  services_hr = excluded.services_hr,
  services_en = excluded.services_en,
  published = excluded.published,
  show_date = excluded.show_date,
  sort_order = excluded.sort_order;
